name: main
on:
  push:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p $HOME/toto/test  # works
      - run: mkdir -p $HOME/titi/test  # doesn't works
        working-directory: $HOME/toto/test
