name: main
on:
  push:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p /home/runner/toto/test  # works
      - run: mkdir -p /home/runner/titi/test  # doesn't works
        working-directory: /home/runner/toto/test
