name: main
on:
  push:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/toto/test  # works
      - run: mkdir -p ~/titi/test  # doesn't works
        working-directory: ~/toto/test
