name: main
on:
  push:
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$HOME"
          mkdir -p ~/toto/test  # work
      - run: |
          echo "$HOME"
          mkdir -p ~/titi/test  # doesn't work
        working-directory: ~/toto/test
